---
# tasks file for oasis-workstation

- name: install elevate.native
  script: install_elevate.ps1

- name: install packages with Chocolatey
  script: chocolatey.ps1 {{ item }}
  with_items:
    - firefox
    - git
    - jdk7
    - notepadplusplus.install
    - vcredist2010
